/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    TinyContainer: typeof import('@opentiny/vue')['Container']
    TinyMindMap: typeof import('@opentiny/vue')['MindMap']
    TinyRichTextEditor: typeof import('@opentiny/vue')['RichTextEditor']
    TinySplit: typeof import('@opentiny/vue')['Split']
    TinyTree: typeof import('@opentiny/vue')['Tree']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
